language: node_js
node_js:
- "0.10"
cache:
  directories:
    - node_modules
before_install:
  - gem install sass
  - npm install -g grunt-cli
install:
  - sudo apt-get install libgif-dev
  - npm install
script:
  - npm test
  - bash ./deploy.sh
branches:
  except:
    -gh-release
    -gh-pages
