language: node_js
node_js:
- "4"
- 6.3.0
cache:
  directories:
    - node_modules
before_install:
  - npm install -g grunt-cli
install:
  - sudo apt-get install libgif-dev
  - npm install
script:
  - npm test
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash ./scripts/deploy.sh
branches:
  except:
    -gh-release
    -gh-pages
env:
  global:
    - GH_REF: github.com/Esri/cedar.git
    - secure: "QU9A0CWiNCqtli84ytRb7OowR9zhZUcD3Ni/2oZr29gM3OMOn4cw5iHxuF+VJPrih0sZgsr68RMHnOs3hC8rC+EkytWnm6tzA7oHOTn7bD2Bs2xdeIuljSdokdb4/TFmmqRxeMlXRymCGbtg3JaZ/aiqbFZ3BATkdprinvvfLLo="
